version: '3'

services:
  web:
    build: .
    command:
      - python src/manage.py runserver 0.0.0.0:8000
      - python src/webSocket/server.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8888:8888"
