# Generated by Django 2.0.4 on 2018-04-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='highlighted',
        ),
    ]
